"""The run ledger's own account of the rounds so far, as two pinned files.

`engine:ledger_render` is the debrief node's input (run-ledger §3.7, D12). It
is an ENGINE producer, so it is bound through the causal routing seam exactly
as `engine:verify_failure` is — `foreman/inputs.py` skips engine producers when
it binds node inputs on purpose, because neither is instance material.

Two things read the render, and they must agree byte for byte:

1. the debrief node, which is told to write `findings.md` and `evidence.json`
   into its attempt directory verbatim;
2. `scripts/verify-debrief.sh`, which compares the files it finds in the
   commit under test against `<render ref>:findings.md` and
   `<render ref>:evidence.json`.

So the render is pinned as a COMMIT whose tree holds exactly those two files,
under a ref named by the task and the attempt (`carriers.LEDGER_RENDER_REF`) —
the only identity the check is given.

It is rendered from the ACTIVATION and GATE records through the neutral seam,
which is the same answer on both backends: the bd rows and the ledger rows
carry the same §3 carriers.

`findings.md` renders the §3.3 FINDINGS of each round as `bdio/findings.py`
orders them: the REVIEWER's own numbered findings first, bounded and
normalised (line endings, invalid UTF-8 replaced) on the carrier its evidence
recorded, then the diagnostics derived from the close
carriers. The ledger inserts exactly those
rows inside the closing transaction, so on that backend the rendered sections
are a projection of the table; on bd, where there is no table, they are the
same derivation over the same carriers. One function, one order — otherwise
the rendered account and the stored one could disagree about a run.
"""

from __future__ import annotations

import hashlib
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import Final

import structlog
from pydantic import BaseModel, ConfigDict, JsonValue, ValidationError

from workflow_interpreter.bdio import (
    ActivationRecord,
    GateRecord,
    InputBinding,
    RootRecord,
)
from workflow_interpreter.bdio.carriers import LedgerRenderBinding
from workflow_interpreter.bdio.findings import Finding, findings_of
from workflow_interpreter.bdio.wire import MintRequest
from workflow_interpreter.foreman.compose import InstanceWiring
from workflow_interpreter.foreman.constants import (
    MSG_RENDER_IDENTITY,
    MSG_RENDER_PIN_FAILURE,
    MSG_RENDER_READ_FAILURE,
)
from workflow_interpreter.foreman.envelope import InputsUnavailable
from workflow_interpreter.schema.loader import canonical_json_bytes
from workflow_interpreter.schema.models import EngineProducer
from workflow_interpreter.supervisor.errors import GitCommandError
from workflow_interpreter.supervisor.gitcmd import GitOutputTooLarge, GitSubcommand
from workflow_interpreter.supervisor.gitio import Git

FINDINGS_FILE: Final[str] = "findings.md"
EVIDENCE_FILE: Final[str] = "evidence.json"
DEBRIEF_FILE: Final[str] = "debrief.md"

RENDER_CAP: Final[int] = 256 * 1024
"""How many bytes of either rendered file are read back. A render is a bounded
summary of bounded records; anything past this is a defect, not a long run."""

_MESSAGE: Final[str] = "wf ledger render {task_id} a{attempt} r{round_no}"
_INDEX: Final[str] = "render.index"
_ENCODING: Final[str] = "utf-8"
_UNKNOWN: Final[str] = "unknown"

_LOG: Final[structlog.stdlib.BoundLogger] = structlog.get_logger(__name__)

_HEADING: Final[str] = "# Findings — {task_id} attempt {attempt}\n"
_PREAMBLE: Final[str] = (
    "\nRendered by the engine from the run ledger. Rounds 1 to {round_no}, in\n"
    "the order the records were written. Do not edit this file: the debrief's\n"
    "own verifier compares it against the render it was produced from.\n"
)
_ROUND_HEADING: Final[str] = "\n## Round {round_no} — {node}\n"
_NO_ROUNDS: Final[str] = "\nNo activation of this attempt has completed yet.\n"
_FINDINGS_HEADING: Final[str] = "\nFindings:\n\n"
_FINDING_LINE: Final[str] = "- {severity}: {text}\n"
_NO_FINDINGS: Final[str] = "- none recorded for this round\n"


class ActivationFacts(BaseModel):
    """What one completed activation is on the record (§3.2, §7)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    findings: tuple[Finding, ...]
    activation_id: str
    node: str
    round_no: int
    outcome: str
    claimed_outcome: str | None
    note: str | None
    verify: tuple[tuple[str, int, int], ...]
    artifact_ref: str | None
    artifact_commit_oid: str | None
    artifact_tree_oid: str | None
    undeclared_effects: tuple[str, ...]


class GateFacts(BaseModel):
    """What one gate of this attempt is on the record (§3.4, §9)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    gate_id: str
    gate_key: str
    gate_node: str
    state: str
    outcome: str | None
    round_no: int | None
    verified_fingerprint: str | None
    payload_digest: str | None
    artifact_ref: str | None
    artifact_oid: str | None


class RenderedRun(BaseModel):
    """The two deterministic files one debrief activation must write."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    findings_md: str
    evidence_json: str

    @property
    def payload_digest(self) -> str:
        """One digest over both files, so a binding names the whole render."""
        hasher = hashlib.sha256()
        hasher.update(self.findings_md.encode(_ENCODING))
        hasher.update(self.evidence_json.encode(_ENCODING))
        return hasher.hexdigest()

    def files(self) -> tuple[tuple[str, str], ...]:
        """The render as `(name, body)` pairs, in the order a tree holds them."""
        return ((EVIDENCE_FILE, self.evidence_json), (FINDINGS_FILE, self.findings_md))


def activation_facts(activation: ActivationRecord) -> ActivationFacts | None:
    """The record's own account of one activation, or nothing if it is unfinished."""
    metadata = activation.metadata
    if not metadata.is_completed or metadata.outcome is None:
        return None
    evidence = metadata.evidence
    artifact = None if evidence is None else evidence.artifact
    return ActivationFacts(
        findings=findings_of(activation),
        activation_id=activation.activation_id,
        node=metadata.node,
        round_no=int(metadata.round_no),
        outcome=metadata.outcome.value,
        claimed_outcome=(
            None
            if evidence is None or evidence.claimed_outcome is None
            else evidence.claimed_outcome.value
        ),
        note=None if evidence is None else evidence.note,
        verify=(
            ()
            if evidence is None
            else tuple(
                (check.cmd, int(check.exit_code), int(check.attempts))
                for check in evidence.verify
            )
        ),
        artifact_ref=None if evidence is None else evidence.outputs_ref,
        artifact_commit_oid=None if artifact is None else artifact.commit_oid,
        artifact_tree_oid=None if artifact is None else artifact.tree_oid,
        undeclared_effects=() if evidence is None else evidence.undeclared_effects,
    )


def gate_facts(gate: GateRecord) -> GateFacts:
    """The record's own account of one gate, signature receipt included (§9)."""
    metadata = gate.metadata
    return GateFacts(
        gate_id=gate.gate_id,
        gate_key=metadata.gate_key,
        gate_node=metadata.gate_node,
        state=metadata.state.value,
        outcome=None if metadata.outcome is None else metadata.outcome.value,
        round_no=None if metadata.round_no is None else int(metadata.round_no),
        verified_fingerprint=metadata.verified_fingerprint,
        payload_digest=metadata.payload_digest,
        artifact_ref=metadata.artifact_ref,
        artifact_oid=metadata.artifact_oid,
    )


def render_run(
    root: RootRecord,
    activations: Sequence[ActivationRecord],
    gates: Sequence[GateRecord],
    *,
    round_no: int,
) -> RenderedRun:
    """Render findings and evidence for every round of this attempt so far.

    Deterministic by construction: the activations are ordered by their
    per-instance `seq`, the gates by theirs, and every value comes from a
    carrier field. Two renders of one unchanged instance are byte-identical,
    which is what lets a check compare a file against the render input.
    """
    identity = root.metadata.run_identity
    task_id = _UNKNOWN if identity is None else identity.task_id
    attempt = 0 if identity is None else identity.attempt
    ordered = sorted(
        (facts for facts in map(activation_facts, activations) if facts is not None),
        key=lambda facts: (
            facts.round_no,
            _seq_of(activations, facts.activation_id),
            facts.activation_id,
        ),
    )
    closed_gates = sorted(
        (gate_facts(gate) for gate in gates), key=lambda facts: facts.gate_key
    )
    return RenderedRun(
        findings_md=_findings_markdown(
            task_id=task_id, attempt=attempt, round_no=round_no, facts=tuple(ordered)
        ),
        evidence_json=_evidence_document(
            task_id=task_id,
            attempt=attempt,
            round_no=round_no,
            facts=tuple(ordered),
            gates=tuple(closed_gates),
        ),
    )


def _seq_of(activations: Sequence[ActivationRecord], activation_id: str) -> int:
    """The per-instance sequence of one activation — its only total order."""
    for activation in activations:
        if activation.activation_id == activation_id:
            return int(activation.metadata.seq)
    return 0  # pragma: no cover - the id came from this very sequence


def _findings_markdown(
    *, task_id: str, attempt: int, round_no: int, facts: Sequence[ActivationFacts]
) -> str:
    """The human-readable account: one section per completed activation."""
    parts = [
        _HEADING.format(task_id=task_id, attempt=attempt),
        _PREAMBLE.format(round_no=round_no),
    ]
    if not facts:
        parts.append(_NO_ROUNDS)
        return "".join(parts)
    for item in facts:
        parts.append(_ROUND_HEADING.format(round_no=item.round_no, node=item.node))
        parts.append(f"\n- activation: {item.activation_id}\n")
        parts.append(f"- outcome: {item.outcome}\n")
        parts.append(f"- claimed: {item.claimed_outcome or 'none'}\n")
        if item.artifact_commit_oid is not None:
            parts.append(f"- artifact commit: {item.artifact_commit_oid}\n")
        # The §3.3 `findings` rows of this round, review rows first and then
        # the diagnostics — the same order the ledger holds them in, because
        # both come from `findings_of` over this one record.
        parts.append(_FINDINGS_HEADING)
        if not item.findings:
            parts.append(_NO_FINDINGS)
        for finding in item.findings:
            parts.append(
                _FINDING_LINE.format(
                    severity=finding.severity.value.upper(), text=finding.text
                )
            )
    return "".join(parts)


def _evidence_document(
    *,
    task_id: str,
    attempt: int,
    round_no: int,
    facts: Sequence[ActivationFacts],
    gates: Sequence[GateFacts],
) -> str:
    """The machine-readable account: canonical JSON, newline-terminated."""
    document: dict[str, JsonValue] = {
        "version": 1,
        "task_id": task_id,
        "attempt": attempt,
        "rounds_so_far": round_no,
        "activations": [item.model_dump(mode="json") for item in facts],
        "gates": [item.model_dump(mode="json") for item in gates],
    }
    return canonical_json_bytes(document).decode(_ENCODING) + "\n"


def bind_render(
    git: Git,
    wiring: InstanceWiring,
    root: RootRecord,
    request: MintRequest,
    *,
    round_no: int,
) -> MintRequest:
    """Pin this attempt's render before a consuming activation's mint is durable.

    The mirror of `verify_feedback.bind_feedback`, and for the same reason: an
    engine input has to exist as a pinned git object BEFORE the activation
    that reads it is recorded, or a crash in between leaves a record naming
    bytes nobody can produce again.
    """
    identity = root.metadata.run_identity
    names = tuple(
        name
        for name in root.index.nodes[request.node].inputs or ()
        if root.index.sources[name].producer == EngineProducer.LEDGER_RENDER
    )
    if not names:
        return request
    if identity is None:
        # An OPTIONAL engine source with nothing to render: a root that pins no
        # run has no attempt directory either, so the activation is minted
        # without the binding and `verify-debrief.sh` refuses it for the same
        # missing identity — loudly, once, where a human reads it.
        _LOG.warning("wf.render.no_identity", root_id=root.root_id, node=request.node)
        return request
    rendered = render_run(
        root,
        wiring.store.reads.list_activations(root.root_id),
        wiring.store.reads.list_gates(root.root_id),
        round_no=round_no,
    )
    try:
        with tempfile.TemporaryDirectory(prefix="wf-render-") as directory:
            staging = Path(directory)
            for name, body in rendered.files():
                (staging / name).write_text(body, encoding=_ENCODING)
            commit = git.commit_directory(
                tuple(name for name, _ in rendered.files()),
                root=staging,
                message=_MESSAGE.format(
                    task_id=identity.task_id,
                    attempt=identity.attempt,
                    round_no=round_no,
                ),
                index_path=staging / _INDEX,
                cwd=wiring.repo_root,
            )
        tree = git.run(
            GitSubcommand.REV_PARSE, f"{commit}^{{tree}}", cwd=wiring.repo_root
        ).text
        proof = LedgerRenderBinding(
            root_id=root.root_id,
            task_id=identity.task_id,
            attempt=identity.attempt,
            round_no=round_no,
            commit_oid=commit,
            tree_oid=tree,
            payload_digest=rendered.payload_digest,
        )
        git.update_ref(proof.ref, commit, cwd=wiring.repo_root)
    except (OSError, ValueError, GitCommandError) as error:
        raise InputsUnavailable(MSG_RENDER_PIN_FAILURE.format(error=error)) from error
    bindings = tuple(
        InputBinding(
            name=name,
            producer_activation_id=root.root_id,
            artifact_ref=proof.ref,
            digest=proof.tree_oid,
            ledger_render=proof,
        )
        for name in names
    )
    return request.model_copy(update={"inputs": (*request.inputs, *bindings)})


def read_render(git: Git, repo_root: Path, binding: InputBinding) -> RenderedRun:
    """Read the pinned render back, refusing anything the binding does not name."""
    proof = binding.ledger_render
    if (
        proof is None
        or binding.artifact_ref != proof.ref
        or binding.digest != proof.tree_oid
    ):
        raise InputsUnavailable(MSG_RENDER_IDENTITY)
    try:
        if git.ref_target(proof.ref, cwd=repo_root) != proof.commit_oid:
            raise InputsUnavailable(MSG_RENDER_IDENTITY)
        bodies = {
            name: git.bounded_bytes(
                GitSubcommand.CAT_FILE,
                "blob",
                f"{proof.tree_oid}:{name}",
                cwd=repo_root,
                limit=RENDER_CAP,
            ).decode(_ENCODING)
            for name in (FINDINGS_FILE, EVIDENCE_FILE)
        }
        rendered = RenderedRun(
            findings_md=bodies[FINDINGS_FILE], evidence_json=bodies[EVIDENCE_FILE]
        )
    except (
        GitCommandError,
        GitOutputTooLarge,
        UnicodeDecodeError,
        ValidationError,
        OSError,
    ) as error:
        raise InputsUnavailable(MSG_RENDER_READ_FAILURE.format(error=error)) from error
    if rendered.payload_digest != proof.payload_digest:
        raise InputsUnavailable(MSG_RENDER_IDENTITY)
    return rendered


def render_envelope_text(rendered: RenderedRun) -> str:
    """The render as the debrief node reads it: both files, verbatim, labelled.

    Fenced with the file name on the fence, because the node's contract is to
    copy these bytes into its attempt directory unchanged — an unlabelled
    concatenation would make that impossible to do correctly.
    """
    return "\n".join(
        (
            "The engine rendered these two files from the run ledger. Write each",
            "one into your attempt directory EXACTLY as it appears here, byte for",
            "byte, and write nothing else into either of them.",
            "",
            f"```{FINDINGS_FILE}",
            rendered.findings_md.rstrip("\n"),
            "```",
            "",
            f"```{EVIDENCE_FILE}",
            rendered.evidence_json.rstrip("\n"),
            "```",
            "",
        )
    )
